### ISSUE TITLE
Apex boosted MM and MMM mod

### ISSUE THREAD

**Issue by Zsashas** [sayterdarkwynd/FrackinRaces#12]
Matter Manipulator Manipulator mod and an Apex character. As soon as I unlocked the first upgrade for the Manipulator (fluid collection, and the first efficiency boost) it lost the extra cursor size, going back to 2x2.

**Comment by sayterdarkwynd** [comment]
nothing I can do about that. They modify the same files.

**Comment by Zsashas** [comment]
I figured that was the case. I just remved MMM.
