### ISSUE TITLE
Neonmelon Jam description (probably) copy-paste error

### ISSUE THREAD

**Issue by Febilian** [sayterdarkwynd/FrackinRaces#125]
Correct text for the description replacement in line with the others would be 

``"A tangy jam made from neonmelons. ^green;Type: Herbivore^reset;"``

Currently it is:

``"Pearlpeas wrapped neatly in a wartweed bundle. ^green;Type: Herbivore^reset;"``

**Comment by sayterdarkwynd** [comment]
thx
