### ISSUE TITLE
Bug with herbivores

### ISSUE THREAD

**Issue by LycanBlackpaw** [sayterdarkwynd/FrackinRaces#53]
Noticed a minor bug playing as a Familiar (herbivore) with Frackin' Races: the effect from eating cooked meat is a buff to them. Grants 1 armor and a small amount of health/energy buff.

**Comment by gamrguy** [comment]
Not an issue; the information must simply be outdated somewhere. Familiars where changed to be omnivores a month ago.

**Comment by LycanBlackpaw** [comment]
So it's outdated both in game and on the github.io page. Meaning, basically everywhere.
